BASE_URL = "https://stellarburgers.nomoreparties.site/"
CREATE_USER_ENDPOINT = "api/auth/register"
DELETE_USER_ENDPOINT = "api/auth/user"
LOGIN_USER_ENDPOINT = "api/auth/login"
EDIT_USER_ENDPOINT = "api/auth/user"
CREATE_ORDER_ENDPOINT = "api/orders"
GET_ORDER_ENDPOINT = "api/orders"
USER = {"name": "ZurujalTempUser", "password": "12345", "email": "ZurujalTemp@YandexTemp.ru"}
USER_ONLY_NAME = {"name": "ZurujalTempUser", "password": "", "email": ""}
USER_ONLY_PASSWORD = {"name": "", "password": "12345", "email": ""}
USER_ONLY_EMAIL = {"name": "", "password": "", "email": "ZurujalTemp@YandexTemp.ru"}
EDIT_USER_NAME = {"name": "EditedName"}
EDIT_USER_PASSWORD = {"password": "EditedPassword"}
EDIT_USER_EMAIL = {"email": "EditedEmail@YandexTemp.ru"}
UNAUTHORIZED_USER_ERROR = "You should be authorised"
ORDER = {"ingredients": ["61c0c5a71d1f82001bdaaa72", "61c0c5a71d1f82001bdaaa6c"]}
ORDER_EMPTY_INGREDIENTS = {"ingredients": []}
ORDER_INCORRECT_INGREDIENTS_HASH = {"ingredients": ["51c0c5a71d1f82001bdaaa72", "51c0c5a71d1f82001bdaaa6c"]}